### ISSUE TITLE
README: Architecture diagram is not rendered fully 

### ISSUE THREAD

**Issue by k-jeon** [deep-diver/image_search_with_natural_language#24]
Hello @deep-diver! I listened to your talk at Google Cloud Innovators Hive in Seoul today. It was a great talk indeed.

By the way, the architecture diagram in the README is not rendered correctly.
 
<img width="1070" alt="Screen Shot 2022-11-22 at 14 19 11" src="https://user-images.githubusercontent.com/92496202/203228401-97626d50-f0d4-4467-9871-5bdc6388f0dd.png">

The source image seems to be okay: https://i.ibb.co/qxdPdJd/architecture-diagram.png

I think resizing the source image may solve the issue.

**Comment by deep-diver** [comment]
Thanks for reporting! @k-jeon 

I will fix it soon :)
